site_name: Omesa
theme: readthedocs

repo_url: http://github.com/cmry/omesa
site_url: http://omesa.readthedocs.org/

site_description: Documentation for reproducible Text Mining research framework.


pages:
- [index.md, Home]
- [faq.md, FAQ]
- [experiment.md, Main, Experiment]
- [featurizer.md, Main, Featurizer]
- [example_simple.md, Examples, End-To-End]
- [example_df.md, Examples, Data-To-Features]
- [example_web.md, Examples, Web App]
- [example_modu.md, Examples, Deployment]
- [containers.md, Backend, Containers]
- [logger.md, Backend, Logger]
- [pipes.md, Backend, Pipes]
- [processor.md, Backend, Taggers]
